sudo: required
services:
  - docker

# before install, test the client whether everything is fine
before_install:
  - docker build -t raghavnayakaasaanjobs/react-test -f ./client/Dockerfile.dev ./client

# testing the above image
# --coverage to exit once tests are done
script:
  - docker run raghavnayakaasaanjobs/react-test npm test -- --coverage

after_success:
  - docker build -t raghavnayakaasaanjobs/multi-client ./client
  - docker build -t raghavnayakaasaanjobs/multi-nginx ./nginx
  - docker build -t raghavnayakaasaanjobs/multi-server ./server
  - docker build -t raghavnayakaasaanjobs/multi-worker ./worker
  # log in to Docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take the above images and push them to Docker hub

  - docker push raghavnayakaasaanjobs/multi-client
  - docker push raghavnayakaasaanjobs/multi-nginx
  - docker push raghavnayakaasaanjobs/multi-server
  - docker push raghavnayakaasaanjobs/multi-worker

